name:         plex
version:      '0.2.0.0'
category:     System
author:       phlummox
copyright:    2018 phlummox
license:      MIT
license-file: LICENSE
github:       phlummox/hs-plex
synopsis:     run a subprocess, combining stdout and stderr
maintainer:   phlummox2@gmail.com
description: |
  Execute a command, redirect stderr into stdout, and return 
  the combined result (optionally, with a timeout). 
  Irritatingly difficult to do using the "process" library.
stability:    experimental

extra-source-files:
- README.md
- CHANGELOG.md 

dependencies:
- base >=4.7 && <5
- async
- deepseq
- bytestring
- unix

flags:
  buildexe:
    description: build the executable
    manual: true
    default: false

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - System.Plex
  - System.Plex.Internal
  - System.Plex.ByteString

# build with:
#     stack build --flag plex:buildExe
executables:
  try-plex:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    # - -with-rtsopts=-N
    when:
    - condition: flag(buildexe)
      then:
        dependencies:
        - async
        - base
        - plex
        - deepseq
        - unix
      else:
        buildable: false

tests:
  plex-test:
    main: Spec.hs
    ghc-options: -Wall
    other-modules: 
    - System.PlexSpec
    - System.Plex.ByteStringSpec
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - plex
    - hspec
    - QuickCheck


